### ISSUE TITLE
Limited data downloaded??

### ISSUE THREAD

**Issue by khushirao** [PJHRobles/Twitter-Get-Old-Tweets-Scraper#5]
through this script i already downloaded 11000 in may 2018  tweets but now June 2018 with same query only 177 tweets downloaded solution??

**Comment by PJHRobles** [comment]
You can check manually if there are only 177 tweets on your twitter account. AFAIK, you can get more than 177 (this is also proven by your statement that you downloaded 11000 tweets last May 2018)

**Comment by khushirao** [comment]
I am downloading tweets related to company by giving  query=PTCL  not tweets of my account.How to resolve it?
